export enum ActivityOrchestratorType {
  DataUriImage = 'DataUriImageOrchestrator',
  DataUriVideo = 'DataUriVideoOrchestrator',
  DeleteEntity = 'DeleteEntityOrchestrator',
  DeleteImage = 'DeleteImageOrchestrator',
  DeleteVideo = 'DeleteVideoOrchestrator',
  MediaProcessAppleIcon = 'MediaProcessAppleIconOrchestrator',
  MediaProcessAppleResource = 'MediaProcessAppleResourceOrchestrator',
  MediaProcessImageVideo = 'MediaProcessImageVideoOrchestrator',
  MediaProcessPostMobileImage = 'MediaProcessPostMobileImageOrchestrator',
  MediaProcessPng = 'MediaProcessPngOrchestrator',
  PostEntity = 'PostEntityOrchestrator',
  PostImage = 'PostImageOrchestrator',
  PostVideo = 'PostVideoOrchestrator',
  UploadImage = 'UploadImageOrchestrator',
  UploadLightroomImage = 'UploadLightroomImageOrchestrator',
  UploadThreeSixtyImage = 'UploadThreeSixtyImageOrchestrator',
  UploadVideo = 'UploadVideoOrchestrator',
}
