export enum ActivityType {
  CreateAppleResource = 'CreateAppleResource',
  CreateIcon = 'CreateIcon',
  CreateImageVideo = 'CreateImageVideo',
  DeleteEntity = 'DeleteEntity',
  DeleteImage = 'DeleteImage',
  DeleteVideo = 'DeleteVideo',
  DimensionImage = 'DimensionImage',
  DimensionVideo = 'DimensionVideo',
  ExifImage = 'ExifImage',
  ExifVideo = 'ExifVideo',
  PostEntity = 'PostEntity',
  PostImage = 'PostImage',
  PostVideo = 'PostVideo',
  SocialMediaPostImage = 'SocialMediaPostImage',
  SocialMediaPostVideo = 'SocialMediaPostVideo',
  TinifyImage = 'TinifyImage',
  UpdateEntitySlug = 'UpdateEntitySlug',
  UpdateImageFileName = 'UpdateImageFileName',
  UpdateVideoFileName = 'UpdateVideoFileName',
}
