export const IMAGE_UPLOADS_BLOB_CONNECTION_STRING =
  'IMAGE_UPLOADS_BLOB_CONNECTION_STRING';
export const IMAGE_UPLOADS_BLOB_CONTAINER_NAME =
  'IMAGE_UPLOADS_BLOB_CONTAINER_NAME';
export const MONGO_DB_CONNECTION_STRING = 'MONGO_DB_CONNECTION_STRING';
export const RESIZE_IMAGE_EXACT_BACKGROUND_COLOR =
  'RESIZE_IMAGE_EXACT_BACKGROUND_COLOR';
