export enum DocumentType {
  About = 'About',
  BestOfChildren = 'BestOfChildren',
  BestOfEvents = 'BestOfEvents',
  BestOfLandscapes = 'BestOfLandscapes',
  BestOfNature = 'BestOfNature',
  BestOfRealEstate = 'BestOfRealEstate',
  Destination = 'Destination',
  Event = 'Event',
  Favorites = 'Favorites',
  PhotoOfTheWeek = 'PhotoOfTheWeek',
  Review = 'Review',
  Reviews = 'Reviews',
  SocialMedia = 'SocialMedia',
}
