export enum DocumentType {
  About = 'About',
  BestOfChildren = 'BestOfChildren',
  BestOfEvents = 'BestOfEvents',
  BestOfLandscapes = 'BestOfLandscapes',
  BestOfNature = 'BestOfNature',
  BestOfRealEstate = 'BestOfRealEstate',
  Destination = 'Destination',
  Event = 'Event',
  Favorites = 'Favorites',
  MediaAppleIcon = 'MediaAppleIcon',
  MediaAppleResource = 'MediaAppleResource',
  MediaPng = 'MediaPng',
  MediaVideo = 'MediaVideo',
  PhotoOfTheWeek = 'PhotoOfTheWeek',
  ReviewMedia = 'ReviewMedia',
  Review = 'Review',
  SocialMedia = 'SocialMedia',
}
