export enum EntityType {
  About = 'About',
  BestOfChildren = 'BestOfChildren',
  BestOfEvents = 'BestOfEvents',
  BestOfLandscapes = 'BestOfLandscapes',
  BestOfNature = 'BestOfNature',
  BestOfRealEstate = 'BestOfRealEstate',
  Destination = 'Destination',
  Event = 'Event',
  Favorites = 'Favorites',
  MediaProcessAppleIcon = 'MediaProcessAppleIcon',
  MediaProcessAppleResource = 'MediaProcessAppleResource',
  MediaProcessImageVideo = 'MediaProcessImageVideo',
  MediaProcessPostMobileImage = 'MediaProcessPostMobileImage',
  MediaProcessPng = 'MediaProcessPng',
  PhotoOfTheWeek = 'PhotoOfTheWeek',
  ReviewMedia = 'ReviewMedia',
  Review = 'Review',
  SocialMedia = 'SocialMedia',
}
