export enum VideoDimensionType {
  Tile = 'Tile',
  Thumbnail = 'Thumbnail',
  Small = 'Small',
  Medium = 'Medium',
  Large = 'Large',
  Facebook = 'Facebook',
  Instagram = 'Instagram',
  LinkedIn = 'LinkedIn',
  GoogleBusiness = 'GoogleBusiness',
  YouTube = 'YouTube',
  ThreeSixtyThumbnail = 'ThreeSixtyThumbnail',
  ThreeSixtySmall = 'ThreeSixtySmall',
  ThreeSixtyMedium = 'ThreeSixtyMedium',
  ThreeSixtyLarge = 'ThreeSixtyLarge',
  ThreeSixtyFacebook = 'ThreeSixtyFacebook',
  ThreeSixtyInstagram = 'ThreeSixtyInstagram',
  ThreeSixtyLinkedIn = 'ThreeSixtyLinkedIn',
  ThreeSixtyGoogleBusiness = 'ThreeSixtyGoogleBusiness',
  ThreeSixtyYouTube = 'ThreeSixtyYouTube',
}
