version: '3.8'

services:
  nginx:
    image: darkrushphotography.azurecr.io/nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443

  api:
    image: darkrushphotography.azurecr.io/api:latest
    container_name: api
    environment:
      - PORT=8081
    ports:
      - 8081:8081
