version: '3.8'

services:
  nginx:
    image: darkrushphotography.azurecr.io/nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443

  website:
    image: darkrushphotography.azurecr.io/website:latest
    container_name: website
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  api:
    image: darkrushphotography.azurecr.io/api:latest
    container_name: api
    environment:
      - PORT=8081
    ports:
      - 8081:8081

  socket:
    image: darkrushphotography.azurecr.io/socket:latest
    container_name: socket
    environment:
      - PORT=8082
    ports:
      - 8082:8082
