export enum EntityType {
  About = 'About',
  BestOfChildren = 'BestOfChildren',
  BestOfEvents = 'BestOfEvents',
  BestOfLandscapes = 'BestOfLandscapes',
  BestOfNature = 'BestOfNature',
  BestOfRealEstate = 'BestOfRealEstate',
  Destination = 'Destination',
  Event = 'Event',
  Favorites = 'Favorites',
  MediaProcessAppleResource = 'MediaProcessAppleResource',
  MediaProcessIcon = 'MediaProcessIcon',
  MediaProcessImageVideo = 'MediaProcessImageVideo',
  MediaProcessPng = 'MediaProcessPng',
  MediaProcessSocialMediaImage = 'MediaProcessSocialMediaImage',
  MediaProcessSocialMediaVideo = 'MediaProcessSocialMediaVideo',
  PhotoOfTheWeek = 'PhotoOfTheWeek',
  ReviewMedia = 'ReviewMedia',
  Review = 'Review',
  SocialMedia = 'SocialMedia',
}
