export enum EntityType {
  About = 'About',
  BestOf = 'BestOf',
  Destination = 'Destination',
  Event = 'Event',
  Favorites = 'Favorites',
  ImagePost = 'ImagePost',
  ImageVideo = 'ImageVideo',
  ThreeSixtyImagePost = 'ThreeSixtyImagePost',
  PhotoOfTheWeek = 'PhotoOfTheWeek',
  ReviewMedia = 'ReviewMedia',
  Review = 'Review',
  SharedPhotoAlbum = 'SharedPhotoAlbum',
  SocialMedia = 'SocialMedia',
}
