export enum ImageDimensionType {
  Thumbnail = 'Thumbnail',
  Small = 'Small',
  Medium = 'Medium',
  Large = 'Large',
  DestinationThumbnail = 'DestinationThumbnail',
  DestinationSmall = 'DestinationSmall',
  DestinationMedium = 'DestinationMedium',
  DestinationLarge = 'DestinationLarge',
  ReviewThumbnail = 'ReviewThumbnail',
  ReviewSmall = 'ReviewSmall',
  Facebook = 'Facebook',
  Instagram = 'Instagram',
  LinkedIn = 'LinkedIn',
  GoogleBusiness = 'GoogleBusiness',
  YouTubeThumbnail = 'YouTubeThumbnail',
  YouTube = 'YouTube',
}
