export enum ImageDimensionType {
  Tile = 'Tile',
  Thumbnail = 'Thumbnail',
  Small = 'Small',
  Medium = 'Medium',
  Large = 'Large',
  Facebook = 'Facebook',
  Instagram = 'Instagram',
  LinkedIn = 'LinkedIn',
  GoogleBusiness = 'GoogleBusiness',
  ThreeSixtyTile = 'ThreeSixtyTile',
  ThreeSixtyThumbnail = 'ThreeSixtyThumbnail',
  ThreeSixtySmall = 'ThreeSixtySmall',
  ThreeSixtyMedium = 'ThreeSixtyMedium',
  ThreeSixtyLarge = 'ThreeSixtyLarge',
  ThreeSixtyFacebook = 'ThreeSixtyFacebook',
  ThreeSixtyInstagram = 'ThreeSixtyInstagram',
  ThreeSixtyLinkedIn = 'ThreeSixtyLinkedIn',
  ThreeSixtyGoogleBusiness = 'ThreeSixtyGoogleBusiness',
  VideoThumbnail = 'VideoThumbnail',
  VideoSmall = 'VideoSmall',
  VideoMedium = 'VideoMedium',
  VideoLarge = 'VideoLarge',
  VideoFacebook = 'VideoFacebook',
  VideoInstagram = 'VideoInstagram',
  VideoLinkedIn = 'VideoLinkedIn',
  VideoGoogleBusiness = 'VideoGoogleBusiness',
}
