export const AUTH0_AUDIENCE = 'https://www.darkrushphotography.com';
export const AUTH0_ISSUER = 'https://darkrushphotography.us.auth0.com/';
export const DEFAULT_ENTITY_GROUP = ' ';
export const DUMMY_MONGODB_ID = '000000000000000000000000';
export const IS_PUBLIC = 'isPublic';
export const JWT = 'jwt';
export const RESIZE_EXACT_FIT_RED_BACKGROUND_COLOR = 30;
export const RESIZE_EXACT_FIT_GREEN_BACKGROUND_COLOR = 30;
export const RESIZE_EXACT_FIT_BLUE_BACKGROUND_COLOR = 30;
