import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { AzureTableStorageModule } from '@nestjs/azure-database';

import {
  AdminEntitiesService,
  CronProcessProvider,
  CronProcessStartProvider,
  CronProcessStartTypeProvider,
  CronProcessStateProvider,
  CronProcessStateUpdateProvider,
  CronProcessTable,
  Document,
  DocumentSchema,
  EntityCreateAllForFolderProvider,
  EntityCreateOneForFolderProvider,
  EntityCreateProvider,
  EntityCreateWatermarkedTypeProvider,
  EntityDeleteProvider,
  EntityFindAllProvider,
  EntityGroupFindProvider,
  EntityGroupProvider,
  EntityOrderProvider,
  EntityPublishProvider,
  ImageAddBlobProvider,
  ImageAddProvider,
  ImageDeleteBlobsProvider,
  ImageExifProvider,
  ImageFindFolderProvider,
  ImageProcessAllProvider,
  ImageProcessOneProvider,
  ImagePublishProvider,
  ImageRemoveAllProvider,
  ImageRemoveOneProvider,
  ImageResizeProvider,
  ImageTinifyProvider,
  ImageUpdateNewProvider,
  ImageVideoEmailProvider,
  SocialMediaPostProvider,
} from '@dark-rush-photography/api/data';
import { AdminEntitiesController } from './admin-entities.controller';

@Module({
  imports: [
    MongooseModule.forFeature([
      { name: Document.name, schema: DocumentSchema },
    ]),
    AzureTableStorageModule.forFeature(CronProcessTable, {
      table: 'CronProcess',
      createTableIfNotExists: true,
    }),
  ],
  controllers: [AdminEntitiesController],
  providers: [
    AdminEntitiesService,
    EntityGroupProvider,
    EntityGroupFindProvider,
    EntityCreateProvider,
    EntityCreateWatermarkedTypeProvider,
    EntityCreateAllForFolderProvider,
    EntityCreateOneForFolderProvider,
    EntityFindAllProvider,
    EntityOrderProvider,
    EntityPublishProvider,
    EntityDeleteProvider,
    ImageUpdateNewProvider,
    ImageFindFolderProvider,
    ImageAddProvider,
    ImageAddBlobProvider,
    ImageProcessAllProvider,
    ImageProcessOneProvider,
    ImageExifProvider,
    ImageTinifyProvider,
    ImageResizeProvider,
    ImageRemoveAllProvider,
    ImageRemoveOneProvider,
    ImageDeleteBlobsProvider,
    ImagePublishProvider,
    ImageVideoEmailProvider,
    SocialMediaPostProvider,
    CronProcessStartProvider,
    CronProcessStartTypeProvider,
    CronProcessProvider,
    CronProcessStateProvider,
    CronProcessStateUpdateProvider,
  ],
})
export class AdminEntitiesModule {}
