export const TILE_IMAGE_WIDTH = 260;
export const TILE_IMAGE_HEIGHT = 186;
export const SMALL_IMAGE_LONGEST_EDGE = 600;
export const MEDIUM_IMAGE_LONGEST_EDGE = 1400;
export const LARGE_IMAGE_LONGEST_EDGE = 2000;
export const SMALL_THREE_SIXTY_IMAGE_LONGEST_EDGE = 1560;
export const MEDIUM_THREE_SIXTY_IMAGE_LONGEST_EDGE = 3640;
export const LARGE_THREE_SIXTY_IMAGE_LONGEST_EDGE = 5200;
