export type ImageDimensionType =
  | 'Tile'
  | 'Thumbnail'
  | 'Small'
  | 'Medium'
  | 'Large'
  | 'ThreeSixtyThumbnail'
  | 'ThreeSixtySmall'
  | 'ThreeSixtyMedium'
  | 'ThreeSixtyLarge'
  | 'Facebook'
  | 'Instagram'
  | 'LinkedIn'
  | 'GoogleBusiness'
  | 'Twitter';
